<?php
/**
 * Alphapay Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Alphapay
 * @package	Alphapay_Payment
 * @copyright	Copyright (c) 2017 Alphapay (http://www.alphapay.ca)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Payment Gateway
 * @package    Alphapay_Payment
 * @author     Alphapay
 * @property   Alphapay Limited
 * @copyright  Copyright (c) 2017 Alphapay Limited (http://www.alphapay.ca)
 */
?>
<span><?php echo $this->getPaymentMethodLabel();?></span>
<!--
<img style="margin-left: 10px; float:right" src="<?php echo $this->getPaymentMethodIcon(); ?>" alt="<?php echo $this->getPaymentMethodLabel() ?>" border="0"/>
-->